# Generated by Django 5.2 on 2025-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('moves', models.PositiveIntegerField()),
                ('time_taken', models.PositiveIntegerField(help_text='Vaqt soniyalarda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
